# Generated by Django 5.2.7 on 2026-03-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_remove_question_user_document_delete_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='publications', to='publications.topic'),
        ),
    ]
