# Generated by Django 5.2.7 on 2026-03-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_document_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='deprecated_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='internal_debug_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
